version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: eveseat_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seat
    ports:
      - "3366:3306"
  redis:
    image: redis:latest
    container_name: eveseat_redis
    command: redis-server --appendonly yes
    volumes:
      - /data
  app:
    build:
      context: ./eveseat_app
    container_name: eveseat_app
    volumes: 
      - ./packages:/var/www/seat/packages
    depends_on:
      - mysql
      - redis
    links:
      - mysql
    ports:
      - "8080:80"