version: "3.2"

services:

  mariadb:
    image: mariadb:10.3
    container_name: seat-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "mariadb-data:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  redis:
    image: redis:5-alpine
    container_name: seat-redis
    restart: always
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  nginx:
    image: eveseat/eveseat-nginx:latest
    depends_on:
      - seat-app
    container_name: seat-nginx
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - "seat-code:/var/www/seat"
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP}:80"
      - "${NGINX_HTTPS}:443"
    command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-app:
    image: eveseat/eveseat-app:latest
    container_name: seat-app
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
      # Remove the comment below to enable SeAT logs to disk.
      #- ./logs:/var/www/seat/storage/logs
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-worker:
    image: eveseat/eveseat-worker:latest
    container_name: seat-worker
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app # for the seat-code volume
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-cron:
    image: eveseat/eveseat-cron:latest
    container_name: seat-cron
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app # for the seat-code volume
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

volumes:
    seat-code:
    redis-data:
    mariadb-data:

networks:
    seat-network:
